### ISSUE TITLE
Linux Security: `Ensure IP forwarding is disabled` control remediation fails on Debian

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnspec-policies#50]
**Describe the bug**
The Linux Security policy's `Ensure IP forwarding is disabled` control includes remediation steps that do not work on Debian.

**To Reproduce**
1. Get a sweet Debian box
2. Add the sysctl configs to the config:

```
net.ipv4.ip_forward = 0

net.ipv6.conf.all.forwarding = 0
```
3. Run the sysctl commands provided:

````
sysctl -w net.ipv4.ip_forward=0

sysctl -w net.ipv6.conf.all.forwarding=0

sysctl -w net.ipv4.route.flush=1

sysctl -w net.ipv6.route.flush=1
```
4. Scan the system

**Expected behavior**
Things pass.

**Comment by mm-weber** [comment]
Can you give me some more info on your testsystem @tas50?
On a vanilla `Debian9/Stretch` it works out of the box:

```bash
vagrant@stretch:~$ uname -a
Linux stretch 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux
```

**Comment by tas50** [comment]
Closing this out as well since it's not something we can repro today
