### ISSUE TITLE
Linux Policy: `Ensure ICMP redirects are not accepted` remediation fails on Debian

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnspec-policies#51]
**Describe the bug**
The remediation steps in the Linux Policy's `Ensure ICMP redirects are not accepted` control do not resolve the error.

3 of the 4 queries are ok, but not all:

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/1015200/196829764-c0d57707-8466-42fa-84ee-981b67dd81c2.png">

**To Reproduce**
1. Add the systctl configs to the file as requested:

```
net.ipv4.conf.all.accept_redirects = 0

net.ipv4.conf.default.accept_redirects = 0

net.ipv6.conf.all.accept_redirects = 0

net.ipv6.conf.default.accept_redirects = 0
```

2. Run the systclt commands as requested:

```
sysctl -w net.ipv4.conf.all.accept_redirects=0

sysctl -w net.ipv4.conf.default.accept_redirects=0

sysctl -w net.ipv6.conf.all.accept_redirects=0

sysctl -w net.ipv6.conf.default.accept_redirects=0

sysctl -w net.ipv4.route.flush=1

sysctl -w net.ipv6.route.flush=1
```
4. Scan the system

**Expected behavior**
The control should pass after implementing the remediation steps

**Comment by mm-weber** [comment]
Just did the same steps as @tas50 but with a reboot in the end.
Could not reproduce the error that way:

```bash
<snip>
✓ Pass:  Ensure ICMP redirects are not accepted
<snip>
```

**Comment by mm-weber** [comment]
```bash
vagrant@stretch:~$ mondoo version
Mondoo 7.3.0 (c00b02ace, 2022-11-08T19:33:51Z)
```

**Comment by tas50** [comment]
Sounds like this one is a me issue so I'm going to close it out. Thanks for diving into things.
