### ISSUE TITLE
All Kubernetes policies need descriptions that explain why the control is important

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnspec-policies#53]
**Is your feature request related to a problem? Please describe.**
When we raise a problem we're telling a user to interrupt their normal work stream to resolve a problem we think is important. We need to make sure we convey that importance to the user though. A description field should include two things:
- What we're checking
- Why it's important to fix this

**Describe the solution you'd like**
Audit all desc fields and make sure they explain what the control checks *and* why it matters to fix the problem.

**Comment by scottford-io** [comment]
Huge 👍  to this! All policies should include the rationale to help users understand the "why" as it may or may not be relevant for their environment.
